# Generated by Django 4.0.3 on 2022-04-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210410_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(to='core.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.BigIntegerField(),
        ),
    ]
